name: Build JARs

on:
  push:
    paths:
      - java/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - run: mvn -B package --file java/SQL/pom.xml
      - run: mvn -B package --file java/SusAmogus/pom.xml

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r SQL.zip java/SQL/target

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r SusAmogus.zip java/SusAmogus/target

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest commit"
          files: |
            *.zip
